version: '2'
services:
  base:
    image: node:10.17.0@sha256:93e9a9283f0e2ead937a8f77a2c72b18f80005c10b57b4f1cfd40d2b3aa6595f
    volumes:
      - customer_nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
  install:
    extends:
      service: base
    command: npm install
volumes:
  customer_nodemodules:
    external: true