version: '2'
services:
  base:
    image: node:10.17.0@sha256:872a4cb1f054fd2f85bbdc9cdf5973ed46e92370e322dbbd4a20afe17530b656
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
  install:
    extends:
      service: base
    command: npm install
volumes:
  nodemodules:
    external: true