version: '2'
services:
  base:
    image: node:10.16.3@sha256:900d982334a1c4218eab398f8728e89e882311c6d457e9e512fa594ed85366c0
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
  install:
    extends:
      service: base
    command: npm install
volumes:
  nodemodules:
    external: true