env: local
secret:
application:
  port: 8100
  session:
      store: redis
      name: sessionID
      secret:
      timeout: 1200000
      securecookies: false
  urls:
      host: host
      api: http://example.com/api
      apiKey:
      frontendapi: http://example.com/api
      frontendapiKey:
  logs:
      level: error
      path: logs
      size: 10240k
      backups: 10
      rotate: daily
  feature:
      bankFeature: true
      dateConfirmation: true
      verify: true
      language: true
  redis:
        host: localhost
        port: 6379
        prefix: spa
        password:
  verify:
        serviceEntityId: serviceEntityId
        verifyServiceProviderHost: http://example.com
        assertionConsumerServiceUrl: http://example.com/verify/response
        matchingServiceEntityId: matchingServiceEntityId
        signingCertificate: signingCertificateString
        encryptionCertificate: encryptionCertificateString
        matchingServiceSigningPrivateKey: matchingServiceSigningPrivateKeyString
        matchingServiceEndpoint: http://example.com/matching-service/POST
        matchingServiceSigningCertificate: matchingServiceSigningCertificateString
        matchingServiceEncryptionCertificate: matchingServiceEncryptionCertificateString

